name: Automatic changelog compile

on:
  push:
  - cron: "0 0 * * *"
      
jobs:
  compile:
    name: Changelog compile

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 25
       
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '>=3.6'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyYaml
    
    - name: Compiles changelogs
      run: python tools/ss13_genchangelog.py html/changelog.html html/changelogs
    
    - name: Commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "HonkBot"
        git commit -m "Automatic changelog compile, [ci skip]" -a || true
        git pull origin master
    
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACTION_SECRET }}
